# This workflow is used during feature development, it will perform lightweight CI and deploy through to the development environment.

name: Feature Development

on:
  workflow_dispatch:
  push:
    branches-ignore: [ "main", "integration/*", "dependabot/*" ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  dotnet-web-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: frasermolyneux/actions/dotnet-web-ci@main
      with:
        dotnet-project: "servers-integration-webapi"
        dotnet-version: 7.0.x
        src-folder: "src"

  publish-nuget-packages:
    environment: NuGet
    runs-on: ubuntu-latest
    needs: [dotnet-web-ci]

    steps:
      - uses: actions/checkout@v3

      - uses: frasermolyneux/actions/publish-nuget-packages@main
        with:
          artifact-name: "nuget-packages"
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  bicep-build-and-apply-dev: 
    environment: Development
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/bicep-build-and-apply
      with:
        environment: dev
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - id: bicep-output
      shell: pwsh
      run: |
        $web_app_name = az deployment group show --name portal-servers-integration-workload-dev --resource-group rg-portal-servers-integration-dev-uksouth --output tsv --query properties.outputs.webAppName.value
        echo "web_app_name=$web_app_name" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

    outputs:
      web_app_name: ${{ steps.bicep-output.outputs.web_app_name }}

  app-service-deploy-dev:
    environment: Development
    runs-on: ubuntu-latest
    needs: [dotnet-web-ci, bicep-build-and-apply-dev]

    steps:
      - uses: actions/checkout@v3

      - uses: frasermolyneux/actions/deploy-app-service@main
        with:
          web-artifact-name: "servers-integration-webapi"
          web-app-name: ${{ needs.bicep-build-and-apply-dev.outputs.web_app_name }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
